### ISSUE TITLE
Ability to run 'npm test' on Windows.

### ISSUE THREAD

**Issue by kruncher** [brianjgeiger/markdown-it-video#18]
It would be nice if the testing lint and mocha tests could be carried out more easily on Windows.

I made the following change to my `package.json` file whilst working on my pull request:

``` diff
-   "test": "make test"
+   "test": "eslint --reset . && mocha"
```

**Comment by brianjgeiger** [comment]
I've rolled this into our `package.json`. Thank you for the suggestion.
