### ISSUE TITLE
What are the hard-coded... codes, in the Prezi output?

### ISSUE THREAD

**Issue by kruncher** [brianjgeiger/markdown-it-video#19]
Whilst working on my fork of this project I couldn't help but notice a couple of hard-coded codes within the Prezi output:

```
landing_data=bHVZZmNaNDBIWnNjdEVENDRhZDFNZGNIUE43MHdLNWpsdFJLb2ZHanI5N1lQVHkxSHFxazZ0UUNCRHloSXZROHh3PT0
```

and

```
landing_sign=1kD6c0N6aYpMUS0wxnQjxzSqZlEB8qNFdxtdjYhwSuI
```

Is it known what these codes are used for? I have never used the Prezi service before and looking at some public content on their site I noticed that these values seem to vary for each video.

**Comment by brianjgeiger** [comment]
I don't personally know. I presume they're some sort of identifier, but I don't use Prezi, personally. Hmm.

**Comment by kruncher** [comment]
Looking at the names of the attributes they seem like they might be tracking codes. Do we know if the embeds will reliably work with these removed entirely?

**Comment by kruncher** [comment]
I have sent an E-mail to Prezi to learn more about these attributes.
