### ISSUE TITLE
Embedding videos using image

### ISSUE THREAD

**Issue by JosefJezek** [brianjgeiger/markdown-it-video#2]
Could you add option for static embedding videos using image?

Like this

``` md
[![IMAGE ALT TEXT](http://img.youtube.com/vi/YOUTUBE_VIDEO_ID/0.jpg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID)
```

Check out the demo...
http://polymer-starter-kit.startpolymer.org

YouTube API
http://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api

Vimeo API
http://stackoverflow.com/questions/1361149/get-img-thumbnails-from-vimeo

Plugin can make responsive images as option like this... ;-)
https://github.com/tatsy/markdown-it-imsize/issues/3

Download image with max resolution from

``` url
http://img.youtube.com/vi/<insert-youtube-video-id-here>/maxresdefault.jpg
```

**Comment by brianjgeiger** [comment]
Hi, Joseph,

I will check out the polymer stuff, although I feel like this and #3 might be better off as a separate plugin.

The current videos are responsive for people using bootstrap (or something that uses the same CSS classes for indicating responsiveness), which I think is a better way to go from a markdown perspective than doing a lot of styling within the markdown.

I don't have really strong opinions on this, and I will give some further thought.

**Comment by kruncher** [comment]
In my opinion polymer stuff would be better off as a separate plugin.
