### ISSUE TITLE
Why set the element id?

### ISSUE THREAD

**Issue by hmil** [brianjgeiger/markdown-it-video#22]
Hi,

First of all thanks a lot for this plugin! This feature is really appreciated.

I see you are giving each video an id like `youtubeplayer`. Is there a good reason for that? It's great to have such a selector handle to apply custom css on the plugin's output but I'd rather have it as a class as there shouldn't be two elements with the same id in an HTML page afaik.

**Comment by brianjgeiger** [comment]
I'm not sure why we have that. It may have been because of the project I forked it from, or it may have been because I was really not paying attention. Regardless, it should be fixed. Thank you!
