### ISSUE TITLE
Explicit license type

### ISSUE THREAD

**Issue by hmil** [brianjgeiger/markdown-it-video#24]
Hi @brianjgeiger ,

Based on the information provided in `package.json` I believe this library is MIT-licensed. Would you mind [including a LICENSE file at the root of the repository](https://help.github.com/articles/licensing-a-repository/)? This saves the guesswork and may enhance your project's visibility.

Thanks!

**Comment by brianjgeiger** [comment]
Added to develop branch, thank you. I'll close this when I do the next release.
