### ISSUE TITLE
Embedding does not work when testing in a local file

### ISSUE THREAD

**Issue by zipang** [brianjgeiger/markdown-it-video#25]
If a run my test in a _local_ html file, i get the following error message in place of the player : 
![capture d ecran 2017-09-04 a 16 26 42](https://user-images.githubusercontent.com/658082/30030527-0afca8d8-918e-11e7-844c-ed73c560c084.png)

That's because the `video_url()` function doesn't return the `http:` protocol which is then replace by `file:`.

**Comment by zipang** [comment]
This is the same as issue #23 : just open a local `.html` test file inside Firefox for example.

**Comment by ThomasAuriel** [comment]
Yep, same issue, same correction. Still waiting for the merge.

**Comment by brianjgeiger** [comment]
Okay, this is merged to `develop` (and, incidentally, I've started using git-flow on this repo). Give that a go and see if it works out better for you. I'm going to try to see if I can get a couple more things cleaned up before I do a full release to `master`.

**Comment by zipang** [comment]
Thxx. That fix was really easy. But the other issue #20 is really much worse.
