### ISSUE TITLE
Second video clones the first even though different

### ISSUE THREAD

**Issue by chris13524** [brianjgeiger/markdown-it-video#27]
Even though the second video is different, it is displayed the same.

```
@[youtube](dQw4w9WgXcQ)
@[vimeo](172927711)
```

If I add a new paragraph in between, then it shows the videos separately as expected.

```
@[youtube](dQw4w9WgXcQ)

@[vimeo](172927711)
```

**Comment by chris13524** [comment]
I see #30 has been merged. Does that mean this issue should be closed?

**Comment by brianjgeiger** [comment]
Indeed, thank you.
