### ISSUE TITLE
Install with bower using `markdown-it-video` not working

### ISSUE THREAD

**Issue by changeweb** [brianjgeiger/markdown-it-video#5]
I guess, since it is a forked repo Bower can not  recognize it by its name.

**Comment by brianjgeiger** [comment]
Probably more that I have to do something to get it working with bower. You could definitely point it to the repo and get it going that way. We're using npm primarily so I hadn't even tested it yet. I'll see what I can find out about getting bower working.

**Comment by brianjgeiger** [comment]
Done
