### ISSUE TITLE
Bugfix: Two video tokens separated by a new line

### ISSUE THREAD

**Issue by convexset** [brianjgeiger/markdown-it-video#9]
The following causes an infinite loop:

```
@[youtube](dQw4w9WgXcQ)
@[youtube](http://www.youtube.com/user/IngridMichaelsonVEVO#p/a/u/1/QdK8U-VIH_o)
```

Here's my fix (original lines commented out), which amounts to "looking at stuff after the cursor":

``` javascript
        // var match = EMBED_REGEX.exec(state.src);
        var balanceSrc = state.src.substr(oldPos);
        var match = EMBED_REGEX.exec(balanceSrc);
```

``` javascript
        // state.pos = state.pos + state.src.indexOf(')');
        state.pos = state.pos + balanceSrc.indexOf(')') - 1;
```

**Comment by brianjgeiger** [comment]
Thank you for this. I'll take a look into it. If you're interested in making a PR to fix this with a test, I could likely get that merged fairly quickly. Otherwise I'll get to it as soon as I can.

**Comment by convexset** [comment]
Take your time. =)

I thought it was just way too minor. (And I don't know enough about
markdown-it to know if I'm missing something)

On Monday, 7 March 2016, Brian J. Geiger notifications@github.com wrote:

> Thank you for this. I'll take a look into it. If you're interested in
> making a PR to fix this with a test, I could likely get that merged fairly
> quickly. Otherwise I'll get to it as soon as I can.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brianjgeiger/markdown-it-video/issues/9#issuecomment-193274173
> .

## 

Regards,
Jeremy Chen

**Comment by chris13524** [comment]
Was this fixed? This doesn't cause an infinite loop for me.

**Comment by brianjgeiger** [comment]
This one does not cause an infinite loop any more, but #20 does.
